package pl.koszela.spring.entities;

public enum CategoryTiles {

    DACHOWKA_PODSTAWOWA,
    DACHOWKA_SKRAJNA_LEWA,
    DACHOWKA_SKRAJNA_PRAWA,
    DACHOWKA_POLOWKOWA,
    DACHOWKA_WENTYLACYJNA,
    KOMPLET_KOMINKA_WENTYLACYJNEGO,
    GASIOR_PODSTAWOWY,
    GASIOR_POCZATKOWY_KALENICA_PROSTA,
    GASIOR_KONCOWY_KALENICA_PROSTA,
    PLYTKA_POCZATKOWA,
    PLYTKA_KONCOWA,
    TROJNIK,
    GASIAR_ZAOKRAGLONY
}